name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build:
    if: "!contains(github.event.pull_request.labels.*.name, 'docs-only')"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python: ["3.9", "3.10", "3.11"]

    steps:
      - uses: compas-dev/compas-actions.build@v4
        with:
          invoke_lint: true
          invoke_test: true
          python: ${{ matrix.python }}
