on:
  push:
    tags:
      - "v*"

name: Create Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        python: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2.0.0
        with:
          miniconda-version: "latest"
          channels: conda-forge
          python-version: ${{ matrix.python-version }}

      - uses: compas-dev/compas-actions.build@v4
        with:
          invoke_lint: true
          invoke_test: true
          use_conda: true
          python: ${{ matrix.python }}

  Publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: compas-dev/compas-actions.publish@v3
        with:
          pypi_token: ${{ secrets.PYPI }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
